# примеры API-запросов

# @baseUrl = http://localhost:8000
@baseUrl = https://online.petrolplus.ru/

### GET {{baseUrl}}/api/public-api/v2/cards/3001331071/transactions
Content-Type: application/json

{
    "Authorization": "NIhMlaThzgqGCgksZGSpZlkNfaiVWEyW",
    "dateFrom": "2020-05-01",
    "dateTo": "2020-05-03",
    "format": "JSON"
}

###
# просмотр объявления
GET {{baseUrl}}/routes/p
Content-Type: application/json

###
# создание объявления
POST {{baseUrl}}/feedback/
Content-Type: application/json

{
    "name": "Nikolay",
    "message": "Great"
}

###
# обновление объявления
PATCH {{baseUrl}}/user_1/1
Content-Type: application/json

{
    "header": "adv_2",
    "description": "text_2",
    "user": "user_1"
}

###
# удаление объявления
DELETE {{baseUrl}}/user_1/1
Content-Type: application/json

###