"""add new table 21/11/2024 temp

Revision ID: 204a97c0be80
Revises: 42665c36b63d
Create Date: 2024-11-22 11:13:55.206719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "204a97c0be80"
down_revision: Union[str, None] = "42665c36b63d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "driver",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "other_route",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "passenger",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "passenger",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "other_route",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "driver",
        "id_point",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
