"""add column ppr_card in table people

Revision ID: 3877e3c500e1
Revises: 9245cc804565
Create Date: 2024-09-27 13:35:42.925317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3877e3c500e1"
down_revision: Union[str, None] = "9245cc804565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("people", sa.Column("ppr_card", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "people", ["ppr_card"])
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "people", type_="unique")
    op.drop_column("people", "ppr_card")
    # ### end Alembic commands ###
