"""change type field date_refuering

Revision ID: 8467149a68d7
Revises: c1185d2668c6
Create Date: 2024-09-29 13:03:09.629934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8467149a68d7"
down_revision: Union[str, None] = "c1185d2668c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "refueling",
        "date_refueling",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "date_refueling",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
