"""change model driver

Revision ID: 9245cc804565
Revises: 48bc8f16bbaa
Create Date: 2024-09-26 09:45:03.089945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9245cc804565"
down_revision: Union[str, None] = "48bc8f16bbaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "driver", sa.Column("where_drive", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "driver",
        "where_drive",
        ["where_drive"],
        ["id_wd"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "driver", type_="foreignkey")
    op.drop_column("driver", "where_drive")
    # ### end Alembic commands ###
