"""add geo

Revision ID: b04e8574514f
Revises: b6a71cbe8cf2
Create Date: 2024-09-06 11:59:58.785688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b04e8574514f"
down_revision: Union[str, None] = "b6a71cbe8cf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("point", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("point", sa.Column("longitude", sa.Float(), nullable=True))
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("point", "longitude")
    op.drop_column("point", "latitude")
    # ### end Alembic commands ###
