"""add unqueConstr field date_refuering

Revision ID: e7610a739410
Revises: 8467149a68d7
Create Date: 2024-09-29 13:39:23.028735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7610a739410"
down_revision: Union[str, None] = "8467149a68d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "refueling_uc",
        "refueling",
        ["id_fuel", "id_people", "quantity", "date_refueling"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("refueling_uc", "refueling", type_="unique")
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(
            precision=2, asdecimal=2, decimal_return_scale=2
        ),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
