"""add table Organization and OtherRoute

Revision ID: f6ed6f991873
Revises: b04e8574514f
Create Date: 2024-09-10 11:01:07.580175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6ed6f991873"
down_revision: Union[str, None] = "b04e8574514f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id_organization", sa.Integer(), nullable=False),
        sa.Column("name_organization", sa.String(length=50), nullable=False),
        sa.Column("id_point", sa.Integer(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_point"], ["point.id_point"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_organization"),
        sa.UniqueConstraint(
            "name_organization", "id_point", name="organization_uc"
        ),
    )
    op.create_table(
        "other_route",
        sa.Column("id_other_route", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id_organization", sa.Integer(), nullable=False),
        sa.Column("id_driver", sa.Integer(), nullable=False),
        sa.Column("where_drive", sa.Integer(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_driver"], ["driver.id_driver"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["id_organization"],
            ["organization.id_organization"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["where_drive"], ["where_drive.id_wd"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_other_route"),
        sa.UniqueConstraint(
            "id_organization",
            "id_driver",
            "where_drive",
            name="other_route_uc",
        ),
    )
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refueling",
        "quantity",
        existing_type=sa.Float(precision=2, asdecimal=2, decimal_return_scale=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_table("other_route")
    op.drop_table("organization")
    # ### end Alembic commands ###
